Feature Request: ETH2x-FLI to ETH2X pair routing
Uniswap/uniswap-interface pull request #1460
Opened 2021-05-06 19:06 UTC by Muhd-Amrullah

This allows direct routing between leveraged tokenset to tokenset pair particularly between ETH2x-FLI and ETH2X pair.

2021-05-07 22:08 UTC, moodysalem requested changes

2021-05-07 22:08 UTC, moodysalem commented on src/constants/index.ts
> +export const ETH2X-FLI = new Token(ChainId.MAINNET,'0xAa6E8127831c9DE45ae56bB1b0d4D4Da6e5665BD', 18, 'ETH2X-FLI','ETH 2x Flexible Leverage Index')
doesnt build because dash

2021-05-07 22:26 UTC, Muhd-Amrullah commented on src/constants/index.ts
> +export const ETH2X-FLI = new Token(ChainId.MAINNET,'0xAa6E8127831c9DE45ae56bB1b0d4D4Da6e5665BD', 18, 'ETH2X-FLI','ETH 2x Flexible Leverage Index')
I've replaced the dash.

2021-05-11 17:45 UTC, Muhd-Amrullah commented
> what's the relationship between ETH2x-FLI and ETH2X? is it your intention in this PR to only add 1-way routing logic for ETH2x but not ETH2x-FLI?

Both are leveraged tokensets that should operate 1:1 at first, however ETH2X will diverge little by little as it takes on a custom tokenset strategy. 

The intention of adding ETH2x-FLI as the connector token is to use it as a base against a range of leveraged tokens such as ETH2X,(next week released BTC2X-FLI) and potentially a combination of others. ETH2x-FLI also has the liquidity it takes to connect and support other 2x leveraged assets. Since their delta (i.e. for every $1 change, it moves $2) is similar, this can potentially reduce some IL. 

The idea is for a person to be able to route "ETH (or other assets) -> ETH2x-FLI -> ETH2X" and back "ETH2X ->ETH2x-FLI -> ETH" (or other assets). Similarly this can be expanded "ETH (or other assets) -> ETH2x-FLI -> BTC2x-FLI" in the future.

2021-05-17 10:46 UTC, Muhd-Amrullah commented
I'm not sure how to handle the vercel's errors. I need some assistance on what to do next to push this forward.

2021-05-19 00:23 UTC, moodysalem commented
closing in favor of https://github.com/Uniswap/uniswap-interface/pull/1644

2021-05-19 00:23 UTC, closed without merging